#!/bin/bash
# Copyright: 2017 - 2018 - MIT License
# Source: https://github.com/envygeeks/devfiles
# Author: Jordon Bedwell
[ "$DEBUG" = "true" ] && set -x
set -e

f=script/script.d/lint
[ "$SKIP_SCRIPTD" != "true" ] && [ -x $f ] && exec $f "$@"
bundle exec rubocop
